sonar_major                              : "5"
sonar_minor                              : "0.1"

sonar_owner                              : "sonar"
sonar_group                              : "sonar"
sonar_shell                              : "/bin/bash"
sonar_base_dir                           : "/usr/local/sonar"

sonar_service_state   : 'started'
sonar_service_enabled : 'yes'
sonar_version         : "{{sonar_major}}.{{sonar_minor}}"
sonar_name            : "sonarqube-{{sonar_version}}"
sonar_archive         : "sonarqube-{{sonar_version}}.zip"
sonar_url             : "http://dist.sonar.codehaus.org/{{sonar_archive}}"
sonar_home_dir        : "{{sonar_base_dir}}/{{sonar_name}}"
sonar_conf_dir        : "{{sonar_home_dir}}/conf"
sonar_bin_dir         : "{{sonar_home_dir}}/bin"
sonar_webapp          : "{{sonar_home_dir}}/webapps"
sonar_war_dir         : "{{sonar_home_dir}}/war/sonar-server/deploy/plugins/"
sonar_ext_dir         : "{{sonar_home_dir}}/extensions/plugins/"
